/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author NNN
 */import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
public class issuebook extends javax.swing.JFrame {

  
    public issuebook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveb = new javax.swing.JButton();
        NAMEL = new javax.swing.JLabel();
        idl = new javax.swing.JLabel();
        issuel = new javax.swing.JLabel();
        duel = new javax.swing.JLabel();
        stid = new javax.swing.JTextField();
        bookt = new javax.swing.JTextField();
        issuet = new com.toedter.calendar.JDateChooser();
        duet = new com.toedter.calendar.JDateChooser();
        closeb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saveb.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        saveb.setText("ISSUE");
        saveb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebActionPerformed(evt);
            }
        });
        getContentPane().add(saveb, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 90, -1));

        NAMEL.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        NAMEL.setText("STUDENT ID");
        getContentPane().add(NAMEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, -1));

        idl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        idl.setText("BOOK ID");
        getContentPane().add(idl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 100, -1));

        issuel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        issuel.setText("ISSUE DATE");
        getContentPane().add(issuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 110, -1));

        duel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        duel.setText("DUE DATE");
        getContentPane().add(duel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 110, -1));
        getContentPane().add(stid, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 263, -1));

        bookt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booktActionPerformed(evt);
            }
        });
        getContentPane().add(bookt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 263, -1));
        getContentPane().add(issuet, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 263, -1));
        getContentPane().add(duet, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 263, -1));

        closeb.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        closeb.setText("CLOSE");
        closeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebActionPerformed(evt);
            }
        });
        getContentPane().add(closeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2024-08-07 at 2.53.17 AM.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void booktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booktActionPerformed

    private void closebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebActionPerformed
        // TODO add your handling code here:
       setVisible(false);
    }//GEN-LAST:event_closebActionPerformed

    private void savebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebActionPerformed
        // TODO add your handling code here:
         SimpleDateFormat f=new SimpleDateFormat("dd-MM-yyy");   
          String id=stid.getText();
          String bookid=bookt.getText();
          String issue=f.format(issuet.getDate());
          String due= f.format(duet.getDate());
          String returnbook="NO";
           try
         {
           Connection con=coonector.getCon();
          Statement st=con.createStatement();
             ResultSet rel=st.executeQuery("select *from newbook  where Bookid='"+bookid+"'");
          
          if(rel.next())
          {
           ResultSet rs=st.executeQuery("select *from studentdata where ID='"+id+"'");
              if(rs.next())
              {
                  st.executeUpdate("insert into issuebook values('"+id+"','"+bookid+"','"+issue+"','"+due+"', '"+returnbook+"')");
                  JOptionPane.showMessageDialog(null,"SUCESSFULLY UPDATE");
                 setVisible(false);
                 new newbook().setVisible(true); 
              }
              else
              {
                  JOptionPane.showConfirmDialog(null, "INCORRECT BOOK ID");
              }
                   
          }
          else
          {
              JOptionPane.showConfirmDialog(null, "INCOORECT STUDENT ID");
          }
         
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null,"COONECTION ERROR");
          
         }
    }//GEN-LAST:event_savebActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issuebook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NAMEL;
    private javax.swing.JTextField bookt;
    private javax.swing.JButton closeb;
    private javax.swing.JLabel duel;
    private com.toedter.calendar.JDateChooser duet;
    private javax.swing.JLabel idl;
    private javax.swing.JLabel issuel;
    private com.toedter.calendar.JDateChooser issuet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton saveb;
    private javax.swing.JTextField stid;
    // End of variables declaration//GEN-END:variables
}
