 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author NNN
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        namel = new javax.swing.JLabel();
        passl = new javax.swing.JLabel();
        loginb = new javax.swing.JButton();
        cancelb = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        passt = new javax.swing.JPasswordField();
        namet = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        namel.setText("USERNAME");
        getContentPane().add(namel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 96, -1));

        passl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        passl.setText("PASSWORD");
        getContentPane().add(passl, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 96, -1));

        loginb.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        loginb.setText("LOGIN");
        loginb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbActionPerformed(evt);
            }
        });
        getContentPane().add(loginb, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 153, -1));

        cancelb.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cancelb.setText("CANCEL");
        cancelb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbActionPerformed(evt);
            }
        });
        getContentPane().add(cancelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 153, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("LOGIN HERE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 160, -1));

        passt.setText("1234");
        getContentPane().add(passt, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 210, -1));

        namet.setText("admin");
        getContentPane().add(namet, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, 210, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1370, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbActionPerformed
        // TODO add your handling code here:
           if(namet.getText().equals("admin")&& passt.getText().equals("1234"))
        {
            setVisible(false);
            new form().setVisible(true);
        }
        else
        {
            namet.setText("");
            passt.setText("");
        }
    }//GEN-LAST:event_loginbActionPerformed

    private void cancelbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbActionPerformed
        // TODO add your handling code here:
       setVisible(false);
    }//GEN-LAST:event_cancelbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginb;
    private javax.swing.JLabel namel;
    private javax.swing.JTextField namet;
    private javax.swing.JLabel passl;
    private javax.swing.JPasswordField passt;
    // End of variables declaration//GEN-END:variables
}
