
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author NNN
 */
public class registrationform extends javax.swing.JFrame {

    /**
     * Creates new form registrationform
     */
    public registrationform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        namel = new javax.swing.JLabel();
        fathl = new javax.swing.JLabel();
        COURSEL = new javax.swing.JLabel();
        FIELDL = new javax.swing.JLabel();
        namet = new javax.swing.JTextField();
        fatt = new javax.swing.JTextField();
        courset = new javax.swing.JComboBox<>();
        itt = new javax.swing.JComboBox<>();
        saveb = new javax.swing.JButton();
        closeb = new javax.swing.JButton();
        idt = new javax.swing.JTextField();
        lstudent = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2024-08-07 at 2.53.17 AM.jpeg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        namel.setText("USERNAME");
        getContentPane().add(namel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 90, -1));

        fathl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        fathl.setText("FATHER'S NAME");
        getContentPane().add(fathl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 120, -1));

        COURSEL.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        COURSEL.setText("COURSE");
        getContentPane().add(COURSEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 70, -1));

        FIELDL.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        FIELDL.setText("FIELD");
        getContentPane().add(FIELDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 50, -1));

        namet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametActionPerformed(evt);
            }
        });
        getContentPane().add(namet, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 250, -1));
        getContentPane().add(fatt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 250, -1));

        courset.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCA", "BSC(CS)", "BTECH", "BA", "BSC", "BBA", "MBBS", " ", " ", " " }));
        courset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursetActionPerformed(evt);
            }
        });
        getContentPane().add(courset, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 90, -1));

        itt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "BUSINESS", "POLITICAL", "GEOGRAPHY", "PSYCHOLOGY", "MECHANICAL", "FASHION", "MEDICAL", " " }));
        getContentPane().add(itt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        saveb.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        saveb.setText("SAVE");
        saveb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebActionPerformed(evt);
            }
        });
        getContentPane().add(saveb, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        closeb.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        closeb.setText("CLOSE");
        closeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebActionPerformed(evt);
            }
        });
        getContentPane().add(closeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));
        getContentPane().add(idt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 250, -1));

        lstudent.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lstudent.setText("Student ID");
        getContentPane().add(lstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 100, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2024-08-07 at 2.53.17 AM.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void coursetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coursetActionPerformed

    private void nametActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametActionPerformed
        // TODO add your handling code here:
     
             
        
    }//GEN-LAST:event_nametActionPerformed

    private void savebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebActionPerformed
         try
         {
             String studentid=idt.getText();
          String username=namet.getText();
          String fathersname=fatt.getText();
          String course=(String)courset.getSelectedItem();
          String field=(String)itt.getSelectedItem();
           
          Connection con=coonector.getCon();
          Statement st=con.createStatement();
          st.executeUpdate("insert into Studentdata values('"+studentid+"','"+username+"','"+fathersname+"','"+course+"','"+field+"')");
          JOptionPane.showMessageDialog(null,"SUCESSFULLY UPDATE");
          setVisible(false);
          new registrationform().setVisible(true);
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null,"student alraedy exists");
             setVisible(false);
             new registrationform().setVisible(true);
         }

    }//GEN-LAST:event_savebActionPerformed

    private void closebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebActionPerformed
        // TODO add your handling code here:
       setVisible(false);
    }//GEN-LAST:event_closebActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrationform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel COURSEL;
    private javax.swing.JLabel FIELDL;
    private javax.swing.JButton closeb;
    private javax.swing.JComboBox<String> courset;
    private javax.swing.JLabel fathl;
    private javax.swing.JTextField fatt;
    private javax.swing.JTextField idt;
    private javax.swing.JComboBox<String> itt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lstudent;
    private javax.swing.JLabel namel;
    private javax.swing.JTextField namet;
    private javax.swing.JButton saveb;
    // End of variables declaration//GEN-END:variables
}
